name: Express.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sefhiroth
          POSTGRES_PASSWORD: probando
          POSTGRES_DB: test_larnu
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --file ./.docker/test/Dockerfile -t test_container .

      - name: run docker tests
        run: docker run --network="host" test_container
